include("structs/make_documents.jl")
include("structs/struct_definitions.jl")
include("structs/doc_fun_block.jl")
include("structs/doc_fun_block_bag.jl")
include("structs/doc_fun_block_voc.jl")
include("structs/gets.jl")
